export const CLASS_LIST = 'CLASS_LIST';
export const ADD_SECTION = 'ADD_SECTION';
export const SECTION_LIST = 'SECTION_LIST';
export const GET_ALL_YEAR_GROUP = 'GET_ALL_YEAR_GROUP';
export const GET_ALL_FORM_GROUP_BY_ID = 'GET_ALL_FORM_GROUP_BY_ID';
export const GET_TEACHER_CLASS_GROUPS = 'GET_TEACHER_CLASS_GROUPS';
export const GET_ALL_TEACHER_LIKE_SEARCH = 'GET_ALL_TEACHER_LIKE_SEARCH';
export const CLASS_GROUP_HOMEWORK = 'CLASS_GROUP_HOMEWORK';
export const GET_ALL_STUDENT_CLASS_GROUP_ID = 'GET_ALL_STUDENT_CLASS_GROUP_ID';
export const GET_ALL_ATTENDANCE_CLASS_GROUP = 'GET_ALL_ATTENDANCE_CLASS_GROUP';
export const GET_EXAM_RESULT_CLASS_GROUP = 'GET_EXAM_RESULT_CLASS_GROUP';
export const GET_ALL_CLASS_GROUP_BY_SUBJECT_ID = 'GET_ALL_CLASS_GROUP_BY_SUBJECT_ID';
export const GET_EXAM_RESUT_DEPARTMENT ='GET_EXAM_RESUT_DEPARTMENT'


