export const TEACHER_ATTENDANCE:string = 'TEACHER_ATTENDANCE';
export const TEACHER_STUDENT_ATTENDANCE:string = 'TEACHER_STUDENT_ATTENDANCE';
export const TEACHER_EXAM_RESULT:string = 'TEACHER_EXAM_RESULT';
export const TEACHER_HOMEWORK_CMS:string = 'TEACHER_HOMEWORK_CMS';


