export const FREELANCE_TEACHER_SUBJECT_LIST = 'FREELANCE_TEACHER_SUBJECT_LIST';
export const FREELANCE_TEACHER_RECORD_CLASS = 'FREELANCE_TEACHER_RECORD_CLASS';
export const FREELANCE_TEACHER_RECORD_CLASS_SESSION_ID = 'FREELANCE_TEACHER_RECORD_CLASS_SESSION_ID';
export const FREELANCE_TEACHER_TOTAL_RECORD_CLASS = 'FREELANCE_TEACHER_TOTAL_RECORD_CLASS';
export const FREELANCE_TEACHER_UPCOMING_SESSION = 'FREELANCE_TEACHER_UPCOMING_SESSION';
export const FREELANCE_TEACHER_UPCOMING_CLASS_CALENDER = 'FREELANCE_TEACHER_UPCOMING_CLASS_CALENDER';
export const CLEAR_TUTOR_SUBJECT_LIST = 'CLEAR_TUTOR_SUBJECT_LIST';
