export const SCHOOL_TEACHER_UPCOMING_SESSION = 'SCHOOL_TEACHER_UPCOMING_SESSION';
export const SCHOOL_TEACHER_UPCOMING_CLASS_CALENDER = 'SCHOOL_TEACHER_UPCOMING_CLASS_CALENDER';
export const SCHOOL_TEACHER_TOTAL_RECORD_CLASS = 'SCHOOL_TEACHER_TOTAL_RECORD_CLASS';
export const SCHOOL_TEACHER_SUBJECT_LIST = 'SCHOOL_TEACHER_SUBJECT_LIST';
export const SCHOOL_TEACHER_RECORD_CLASS_SESSION_ID = 'SCHOOL_TEACHER_RECORD_CLASS_SESSION_ID';
export const SCHOOL_TEACHER_RECORD_CLASS = 'SCHOOL_TEACHER_RECORD_CLASS';
export const GET_TEACHER_HOMEWORK_BY_TEACHER_ID = 'GET_TEACHER_HOMEWORK_BY_TEACHER_ID';
export const GET_TEACHER_EXAM_RESULT = 'GET_TEACHER_EXAM_RESULT';
export const GET_ALL_CLASS_GROUP_OF_DEPARTMENT = 'GET_ALL_CLASS_GROUP_OF_DEPARTMENT';
export const GET_EVENT_BY_DEPARTMENT_SUCCESS = 'GET_EVENT_BY_DEPARTMENT_SUCCESS';
export const GET_ALL_TERMS = 'GET_ALL_TERMS';

