export const STUDENT_INFO = 'STUDENT_INFO';
export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT';
export const STUDENT_DETAILS = 'STUDENT_DETAILS';
export const STUDENT_SEARCH = 'STUDENT_SEARCH';
export const STUDNET_ATTENDANCE = 'STUDNET_ATTENDANCE';
export const STUDENT_EXAM = 'STUDENT_EXAM';
export const STUDENT_HOMEWORK = 'STUDENT_HOMEWORK';
export const STUDENT_TERM_RESULT = 'STUDENT_TERM_RESULT';
export const STUDENT_MORE_HOMEWORK = 'STUDENT_MORE_HOMEWORK';
export const GET_ALL_STUDENT_BY_CLASS_GROUP_ID = 'GET_ALL_STUDENT_BY_CLASS_GROUP_ID';


