export const SUBJECT_LIST = 'SUBJECT_LIST';
export const SUBJECT_LIST_BY_DEPARTMENT_ID = 'SUBJECT_LIST_BY_DEPARTMENT_ID';
export const SUBJECTS_GROUP_LIST = 'SUBJECTS_GROUP_LIST';
export const CLASS_GROUP_LIST = 'CLASS_GROUP_LIST';
