export const SCHOOL_LIST = 'SCHOOL_LIST';
export const VIDEO_LIST = "VIDEO_LIST";
export const ADMIN_TEACHER_LIST = "ADMIN_TEACHER_LIST";
export const ADMIN_STUDENT_LIST = "ADMIN_STUDENT_LIST";
export const ADMIN_PARENTS_LIST = "ADMIN_PARENTS_LIST";
export const ADMIN_ALL_USERS_COUNT = "ADMIN_ALL_USERS_COUNT";
export const TEACHER_DETAILS_SUPER = "TEACHER_DETAILS_SUPER";
export const STUDENT_DETAILS_SUPER = "STUDENT_DETAILS_SUPER";
export const SCHOOL_DETAILS_SUPER = "SCHOOL_DETAILS_SUPER";
export const PARENT_DETAILS_SUPER = "PARENT_DETAILS_SUPER";




